/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package janela;

import javax.swing.JOptionPane;
import java.util.Iterator;
import docentes.Docentes;
import java.nio.file.Path;
import javax.swing.table.DefaultTableModel;
import persistencia.ContratoDepatNome;
import persistencia.DepartamentoTitulaNome;
import persistencia.OrdenaMatricula;
import persistencia.OrdenaNome;
import persistencia.OrdernaDepNome;

import persistencia.TitulacaoNome;


/**
 *
 * @author Yara
 */
public class JanelaSereia extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public JanelaSereia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGridAlunos = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButtonMatricula = new javax.swing.JButton();
        departamentoNome = new javax.swing.JButton();
        titulacaoNome = new javax.swing.JButton();
        departamentoTitulacaoNome = new javax.swing.JButton();
        contratoDepartamentoNome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTA DE ALUNOS");

        jTableGridAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MATRICULA", "NOME", "DEPARTAMENTO", "TITULACAO", "CONTRATO", "H. DEFINIDO", "H. ATUAL"
            }
        ));
        jScrollPane1.setViewportView(jTableGridAlunos);

        jToggleButton1.setText("ORDENADO PELO NOME");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButtonMatricula.setText("ORDENA MATRICULA");
        jButtonMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatriculaActionPerformed(evt);
            }
        });

        departamentoNome.setText("ORDENA Depar. Nome");
        departamentoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoNomeActionPerformed(evt);
            }
        });

        titulacaoNome.setText("Orde.  Titulaçao Nome");
        titulacaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulacaoNomeActionPerformed(evt);
            }
        });

        departamentoTitulacaoNome.setText("departamento tirulação, nome ");
        departamentoTitulacaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoTitulacaoNomeActionPerformed(evt);
            }
        });

        contratoDepartamentoNome.setText("contrato departamento nome");
        contratoDepartamentoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoDepartamentoNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonMatricula)
                        .addGap(26, 26, 26)
                        .addComponent(departamentoNome)
                        .addGap(37, 37, 37)
                        .addComponent(titulacaoNome)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(departamentoTitulacaoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contratoDepartamentoNome)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButtonMatricula)
                    .addComponent(departamentoNome)
                    .addComponent(titulacaoNome))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departamentoTitulacaoNome)
                    .addComponent(contratoDepartamentoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void imprimirNaGrid(Iterator<Docentes> arquivo){
        try{
            DefaultTableModel model =  (DefaultTableModel) jTableGridAlunos.getModel();
            model.setNumRows(0);
            while(arquivo.hasNext()){
                String[] linha = new String[7];
                Docentes obj = arquivo.next();
                linha[0]= obj.getMatricula();
                linha[1]= obj.getNome();
                linha[2]= obj.getDepartamento();
                System.out.println(linha[2]);
                linha[3]= obj.getTitulacao();
                linha[4]= obj.getTipoContrato();
                linha[5]= obj.getCgDefinida();
                linha[6]= obj.getCgAtual();
                model.addRow(linha);
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "C:\\Users\\Iara\\Desktop\\yara\\ordenador.txt";
            OrdenaNome objeto = new OrdenaNome(nome);
            imprimirNaGrid(objeto.listagem());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void departamentoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoNomeActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "C:\\Users\\Iara\\Desktop\\yara\\ordenador.txt";
            OrdernaDepNome objeto = new OrdernaDepNome(nome);
            imprimirNaGrid(objeto.listagem());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_departamentoNomeActionPerformed

    private void titulacaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulacaoNomeActionPerformed
        // TODO add your handling code here:
        try {
            String nome = "C:\\Users\\Iara\\Desktop\\yara\\ordenador.txt";
            TitulacaoNome objeto = new TitulacaoNome(nome);
            imprimirNaGrid(objeto.listagem());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }

    }//GEN-LAST:event_titulacaoNomeActionPerformed

    private void jButtonMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatriculaActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "C:\\Users\\Iara\\Desktop\\yara\\ordenador.txt";
            OrdenaMatricula objeto = new OrdenaMatricula(nome);
            imprimirNaGrid(objeto.listagem());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonMatriculaActionPerformed

    private void departamentoTitulacaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoTitulacaoNomeActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "C:\\Users\\Iara\\Desktop\\yara\\ordenador.txt";
            DepartamentoTitulaNome objeto = new DepartamentoTitulaNome(nome);
            imprimirNaGrid(objeto.listagem());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
        
    }//GEN-LAST:event_departamentoTitulacaoNomeActionPerformed

    private void contratoDepartamentoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoDepartamentoNomeActionPerformed
         // TODO add your handling code here:
        try{
            String nome = "C:\\Users\\Iara\\Desktop\\yara\\ordenador.txt";
            ContratoDepatNome objeto = new ContratoDepatNome(nome);
            imprimirNaGrid(objeto.listagem());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_contratoDepartamentoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaSereia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaSereia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaSereia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaSereia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaSereia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contratoDepartamentoNome;
    private javax.swing.JButton departamentoNome;
    private javax.swing.JButton departamentoTitulacaoNome;
    private javax.swing.JButton jButtonMatricula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGridAlunos;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton titulacaoNome;
    // End of variables declaration//GEN-END:variables
}
